
# Setup
name:   atrakic.github.io
description: >
  my random echo stuff
meta_description: "yet another jekyll site"
#baseurl:    ""
paginate:   3

# RSS
url:        "/"
author:     "Admir Trakic" 

# Build settings
markdown: kramdown
highlighter: rouge
logo: false

# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
# permalink:        pretty
timezone: Europe/Copenhagen
relative_permalinks: true

gems: 
  - jekyll-paginate
#  - jekyll-gist
#  - jekyll-assets
#  - jekyll-sitemap
###  - html-proofer

# About
twitter_username: admirtrakic
github_username:  atrakic

# Excude stuff
exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - Makefile
  - docker-compose.yml
  - Dockerfile

# Custom vars
version:             0.1.1


