assets:
  compress:
      css: true
      js: true
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md

ga_analytics: # Add Google Analytics tracking code

gems:
#  - jekyll-assets
#  - jekyll-sitemap


permalink: pretty

# Site settings
name: atrakic_github_io
url: # Add your site url
title: atrakic.github.io
email: xomodo@gmail.com
description: > 
  my random echo stuff.  
baseurl: ""
url: "" 
twitter_username: admirtrakic
github_username:  atrakic

# Build settings
markdown: kramdown
theme: minima
#theme: jekyll-theme-cayman

