# Site settings
name: atrakic_github_io
title: atrakic.github.io
email: xomodoat@gmaildot.com
description: > 
  my random echo stuff.  
baseurl: ""
url: "" 
twitter_username: admirtrakic
github_username:  atrakic
permalink: pretty

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - README.md
  - CNAME
  - LICENSE.md
  - vendor
  - deploy

gems:
#  - jekyll-assets
#  - jekyll-sitemap
  -  html-proofer

# Build settings
markdown: kramdown
theme: minima

