services:
  web:
    image: nginx:alpine
    container_name: web
    ports:
      - "8080:80"
    environment:
      - USER=foo
    command: /bin/sh -c "/app $${USER} && mv -f index.html /usr/share/nginx/html && nginx -g 'daemon off;'"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m
      timeout: 20m
      retries: 20
    volumes:
      - ./app:/app
      - ./_site/css:/usr/share/nginx/html/css:ro
