// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func index(name string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(name)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `index.templ`, Line: 8, Col: 16}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><link rel=\"stylesheet\" href=\"./style.css\"><style>\n\t\t\t\t.cicd, .security, .kubernetes { font-size: 14px; }\n\t\t\t\t.http, .docker, .git { font-size: 16px; }\n\t\t\t\t.javascript, .dotnet, .nodejs, .aws, .azure, .sql, .nosql, .python, { font-size: 18px; }\n\t\t\t\t.data, .devops, .cloud, .linux { font-size: 20px; }\n\t\t\t\t.data { transform: rotate(-10deg); }\n\t\t\t\t.http { transform: rotate(-8deg); }\n\t\t\t\t.cicd { transform: rotate(10deg); }\n\t\t\t\t.security { transform: rotate(-4deg); }\n\t\t\t\t.cloud, .dotnet { transform: rotate(6deg); }\n\t\t\t</style></head><body><div class=\"word-cloud\"><span class=\"data\">Data</span> <span class=\"http\">HTTP</span> <span class=\"devops\">DevOps</span> <span class=\"cicd\">CI/CD</span> <span class=\"security\">Security</span> <span class=\"cloud\">Cloud computing</span> <span class=\"docker\">Docker</span> <span class=\"kubernetes\">Kubernetes</span> <span class=\"git\">Git</span> <span class=\"javascript\">JavaScript</span> <span class=\"nodejs\">Node.js</span> <span class=\"aws\">AWS</span> <span class=\"azure\">Azure</span> <span class=\"sql\">SQL</span> <span class=\"dotnet\">Dotnet</span> <span class=\"python\">Python</span> <span class=\"golang\">Golang</span> <span class=\"linux\">Linux</span></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
